### ISSUE TITLE
Display password in dashup

### ISSUE THREAD

**Issue by fidsusj** [raphaelmue/dashup#58]
Is it possible to display the password of a user in the account setting menu? If I understood it right, then the stored hash in the database is only one way, isn't it?

**Comment by raphaelmue** [comment]
No it's not possible. Hashes are always one-way. This prevents hackers from stealing the users passwords. The hashes are useless, because hackers cannot login if they only know the users hashed password. 
Besides this is a huge security lack. If the user forgets to log out and another person opens the dashup settings menu, he can now see his plain password. 
Does that answer your question?
